version: "3"

networks:
  db:
  nginx:

volumes:
  db_data:

services:
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      SERVER_NAME: localhost
    ports:
      - 80:80
    networks:
      - nginx
    depends_on:
      - python
  python:
    build: ./python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/eduargenton/eng_soft2/Let-s-Party-Now/:/app
    networks:
      - db
      - nginx
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.7.8
    restart: always
    environment:
      MYSQL_DATABASE: lpn
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db
