version: "3"

networks:
  db:
  nginx:
  front:

volumes:
  db-data:

services:
  nginx:
    image: nginx:1.22.1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      SERVER_NAME: localhost
    ports:
      - 8080:80
    networks:
      - web
    depends_on:
      - python
    restart: unless-stopped
  python:
    build: ./python
    networks:
      - db
      - web
      - front
    depends_on:
      - mariadb
    restart: unless-stopped
  wordpress:
    image: wordpress:php8.2-apache
    networks:
      - front
      - web
    restart: unless-stopped
    depends_on:
      - python
      - mariadb
  mariadb:
    image: mariadb:10.6.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lpn
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db
    restart: unless-stopped
